paths:
  public: "public"
groups:
  scripts:
    paths:
      - app/scripts
    concat:
      "/assets/scripts/app.js": "app/**/*.{js,coffee}"
      "/assets/scripts/vendor.js": "vendor/**/*.{js,coffee}"
      "/assets/scripts/common.js": "{app/templates/**/view.{js,coffee},app/scripts/*.{js,coffee},app/scripts/common/**/*.{js,coffee}}"
    order:
      - vendor/jquery.js
      - ...
      - app/scripts/app.coffee
  styles:
    paths:
      - app/styles
    concat:
      "/assets/styles/app.css": "app/styles/**/[a-z]*.{css,scss,sass}"
      "/assets/styles/common.css": "{app/styles/**/[a-z]*.{css,scss,sass},app/templates/**/view.{css,scss,sass}}"
  images:
    paths:
      - app/images
    sprite:
      "../app/images/icons.scss": "app/images/**/*.png"
  views:
    paths:
      - app/views
    copy:
      "templates/layout": "app/views/**/*.{htm,html,hbs}"
      "templates/": "app/templates/**/*.{htm,html,hbs}"
  templates:
    paths:
      - app/templates
#    precompile:
#      "../vendor/templates.js": "app/templates/**/*.hbs"
modules:
  wrapper: cmd
  ignored: vendor/**/*
  definition: /assets/scripts/common.js
sprites:
  path: /assets/images/
  selector: .icon-
notification: true
bundles:
  jquery.js:
    version: 1.10.2
    url: http://code.jquery.com/jquery-1.10.2.js
  handlebars.js:
    version: 1.0.0
    url: https://raw.github.com/wycats/handlebars.js/1.0.0/dist/handlebars.runtime.js
environments:
  production:
    revision:
      manifest: "manifest.yml"
      files:
        - index.html
